spring:
  application:
    name: spring-boot-904
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: hr
    password: hr

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    basename: i18n/messages
    default: ar
  security:
    user:
      name: eslam
      password: eslam123

server:
  port: 9090

token:
  secret: dskfsdjkfkjhsfdkjfjh3432432@#$#@23
  time: 24h