server:
  port: 9090

# Oracle Database Configuration
spring:
  security:
    user:
      name: eslamYml
      password: eslamYml123
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: hr
    password: hr
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    basename: i18n/messages

token:
  secret: dafkhkjsdLHKDJSH2332DSFAMN@#@#$!
  time: 24h
