server:
  port: 8081

spring:
  security:
    user:
      name: eslam
      password: 123
  application:
    name: spring-boot-910
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: hr
    password: hr
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    basename: i18n/messages

token:
  secret: sdadasdas##@##123232ASsaQWQQWQ@#!
  time: 24h
