spring:
  application:
    name: Restaurant
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    basename: i18n/messages
    local-default: en
  main:
    allow-circular-references: true
server:
  port: 8085

token:
  secret: kkkjgkhkd669$#65@#fghdfyhrtyerytryrtydfgjfg
  time: 10h

